### ISSUE TITLE
Cmp performance

### ISSUE THREAD

**Issue by Bleksak** [adalessa/laravel.nvim#103]
Hi, I'm using the "feature/containers" branch, and I have a performance suggestion for cmp completion.

You could utilize some caching mechanism for storing views, configs and routes (create the cache on plugin load, and update every time a file is saved/created/deleted using Autocmds). I may try to implement this and open a PR soon if you don't have the time.

**Comment by adalessa** [comment]
Hey thanks for the suggestion.
Regarding caching yes I am still investigating the best times to invalidate them/renew them.
If you have suggestions/pr they are welcome.

**Comment by adalessa** [comment]
Hey @Bleksak I have beek working more on this. with a change on how the cache was being manage, and internal changes moving to promises instead of all callbacks now in the development branch these changes are available.

**Comment by Bleksak** [comment]
Thank you, it works perfectly, I'm closing this issue.
