### ISSUE TITLE
LazyVim can' t load config

### ISSUE THREAD

**Issue by ziriuz84** [adalessa/laravel.nvim#111]
I'm using this plugin with LazyVim distro 12.42.0 on neovim 0.10.2 and it gives me this error

```
.../.local/share/nvim/lazy/laravel.nvim/lua/laravel/app.lua:187: Could not load module laravel.repositories.cache_views_repository

# stacktrace:
  - /laravel.nvim/lua/laravel/app.lua:187 _in_ **make**
  - /laravel.nvim/lua/laravel/app.lua:210 _in_ **app**
  - /laravel.nvim/lua/laravel/providers/completion_provider.lua:11 _in_ **boot**
  - /laravel.nvim/lua/laravel/app.lua:144 _in_ **start**
  - /laravel.nvim/lua/laravel/init.lua:6 _in_ **setup**
```

Maybe something with latest update to 3.0?

**Comment by adalessa** [comment]
Hi @ziriuz84 with the release of 3.0 there is a new dependency of https://github.com/kevinhwang91/promise-async did you add it ?

**Comment by ziriuz84** [comment]
Ah, doh! I didn't see it, sorry :sweat_smile:

**Comment by adalessa** [comment]
No problem I tired to mark it, but I know it could happen, that it was my first guest.
Have a good one.

**Comment by kemboi22** [comment]
how do i install this using https://github.com/kevinhwang91/promise-async

also which plugin can i install so that blade can be formatted

**Comment by adalessa** [comment]
Hi @kemboi22 assuming that you have you configuration with lazy you need to add it to the list of dependencies,
```lua
dependencies = {
    "tpope/vim-dotenv",
    "nvim-telescope/telescope.nvim",
    "MunifTanjim/nui.nvim",
    "kevinhwang91/promise-async",
  },
  ```
  More detail here https://adalessa.github.io/laravel-nvim-docs/docs/getting-started/
  
  Related to format blade files there is the program https://github.com/shufo/blade-formatter
  For a plugin, it can be trigger from none-ls, but all of this is outside of the scope of this plugin.

**Comment by kemboi22** [comment]
Thank you for that i have been able to install it using luarocks
