### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by pojokcodeid** [adalessa/laravel.nvim#118]
Hai,

I have error 
```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:                                                                          ...m-data/lazy/laravel.nvim/lua/laravel/services/status.lua:40: attempt to index local 'info' (a nil value)                                                    stack traceback:                                                                                                                                                       ...m-data/lazy/laravel.nvim/lua/laravel/services/status.lua:40: in function <...m-data/lazy/laravel.nvim/lua/laravel/services/status.lua:39>
```
My Config
```
	{
		"adalessa/laravel.nvim",
		dependencies = {
			"tpope/vim-dotenv",
			"nvim-telescope/telescope.nvim",
			"MunifTanjim/nui.nvim",
			"kevinhwang91/promise-async",
		},
		cmd = { "Laravel" },
		keys = {
			{ "<leader>L", "", desc = " 󰫐 Laravel" },
			{ "<leader>La", ":Laravel artisan<cr>" },
			{ "<leader>Lr", ":Laravel routes<cr>" },
			{ "<leader>Lm", ":Laravel related<cr>" },
		},
		event = { "VeryLazy" },
		opts = {},
		config = true,
	},

```
Neovim Version = 0.10.1
Terminal = Wezterm
OS         = Windows 11
![image](https://github.com/user-attachments/assets/34776b92-368e-43b3-96e4-7694fa7fc1c8)

![image](https://github.com/user-attachments/assets/b0790431-1b55-4182-a5f4-c548ab1f4bab)

![image](https://github.com/user-attachments/assets/1866a1ae-8221-43d2-8ba3-ff1ee729eb66)

Thanks

**Comment by adalessa** [comment]
Hi @pojokcodeid I have pushed a change https://github.com/adalessa/laravel.nvim/commit/fab6b423b7d4730e68ee1411be426794a9da2d9b 
Looks for your case the command about is not returning what is expected.
What version of laravel are you using ?
Now it should not fail, but could be missing the status info for status bar, 
Please test and let me know.

**Comment by pojokcodeid** [comment]
I'm using laravel 11
now returns an error if opening a file

![image](https://github.com/user-attachments/assets/051649ed-0d3e-41d0-9bef-c2718b4f4dc9)

**Comment by adalessa** [comment]
Thanks for reporting this, I have pushed a change to properly handle the error.
The underline error is in your system where the config defines to use sqlite but your environment does not have the driver.

**Comment by pojokcodeid** [comment]
- after synchronization
- now returns a different error message
![image](https://github.com/user-attachments/assets/03e34aa8-2f6c-4504-b16c-de8f802898e1)

**Comment by adalessa** [comment]
I think this is related to another case, not sure what happen there, but I added code to catch it. Please test

**Comment by pojokcodeid** [comment]
thanks
already ok
