### ISSUE TITLE
Failid to run config for laeravel.nvim

### ISSUE THREAD

**Issue by pojokcodeid** [adalessa/laravel.nvim#119]
Hai,

Neovim Version = 0.10.1
Terminal  = Wezterm
OS    = Windows 11

I have error like this
![image](https://github.com/user-attachments/assets/9a3b76d4-46dd-4ddf-93b1-8c90792e5996)
![image](https://github.com/user-attachments/assets/3b5624a6-fd68-4796-9bbc-0d756aefe6bc)
![image](https://github.com/user-attachments/assets/4bad84d6-2b33-40a6-8f3c-3422975e2372)

My Config
```
	{
		"adalessa/laravel.nvim",
		enabled = is_laravel_project(), -- pastikan membuka laravel project
		dependencies = {
			"tpope/vim-dotenv",
			"nvim-telescope/telescope.nvim",
			"MunifTanjim/nui.nvim",
			"kevinhwang91/promise-async",
		},
		cmd = { "Laravel" },
		keys = {
			{ "<leader>L", "", desc = " 󰫐 Laravel" },
			{ "<leader>La", ":Laravel artisan<cr>" },
			{ "<leader>Lr", ":Laravel routes<cr>" },
			{ "<leader>Lm", ":Laravel related<cr>" },
		},
		event = { "VeryLazy" },
		opts = {},
		config = true,
	},

```

**Comment by adalessa** [comment]
Strange, there only runs for the query set native function, could be from your configuration treesitter has not loaded php treesitter properly.  could you add the dependencies to treesitter so it ensure is loaded before laravel plugin ?

**Comment by pojokcodeid** [comment]
Thaks,
now it's ok
after adding 
“nvim-lua/plenary.nvim”,
“nvim-treesitter/nvim-treesitter”,
to the dependencies
