### ISSUE TITLE
UnhandledPromiseRejection when sail is not running

### ISSUE THREAD

**Issue by mimre25** [adalessa/laravel.nvim#120]
I'm getting the following error when sail is not running:

```console
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
Sail is not running.

You may Sail using the following commands: './vendor/bin/sail up' or './vendor/bin/sail up -d'
```

Which is fine on it's own. 
However, the error keeps repeating upon entering any file.
This makes the plugin really annoying when navigating a code-base without the corresponding sail/docker container running.

I think it should just alert once upon entering the first file and leave it at that.

Anything I could configure to solve this issue?

**Comment by adalessa** [comment]
I will look into this, thanks for the suggestion.  Hopefully will solve it soon.

**Comment by adalessa** [comment]
@mimre25 I have pushed a quickfix into the main branch, please update and test it. for now will be ignoring the error for future versions will be smarter to notify only once, I need to think if it should be disable and the ability to re-enable. for now is ignored, once you get sail up it will start working.

**Comment by mimre25** [comment]
Works fine, just like you described it, I don't get any error message.

For me that's also fine, because I will get the error whenever I try to run any Laravel command.

So maybe the quickfix is actually a proper fix? :thinking: 

Thanks for the quick reaction :slightly_smiling_face:

**Comment by adalessa** [comment]
Glad to hear that it's working for you. It can stay like this for a longer time, but not exactly how I would like to keep in  the long term, for now I will close the ticket, but will keep it in mind what I would like to change.
Thanks for reporting this.
