### ISSUE TITLE
Attempt to concatenate local 'env_name' (a nil value)

### ISSUE THREAD

**Issue by kcaashish** [adalessa/laravel.nvim#26]
My config is as suggested:
```lua
  {
    "adalessa/laravel.nvim",
    dependencies = {
      "nvim-telescope/telescope.nvim",
      -- which-key integration
      {
        "folke/which-key.nvim",
        opts = {
          defaults = {
            ["<leader>cp"] = { name = "+php" },
          },
        },
      },
    },
    cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
    keys = {
      { "<leader>cpa", ":Laravel artisan<cr>", desc = "Artisan" },
      { "<leader>cpr", ":Laravel routes<cr>", desc = "Routes" },
      {
        "<leader>cpt",
        function()
          require("laravel").app.sendToTinker()
        end,
        mode = "v",
        desc = "Laravel Application Routes",
      },
    },
    ft = { "blade", "php" },
    config = function()
      require("laravel").setup()
      require("telescope").load_extension("laravel")
    end,
  }
```
I am getting this error message:
<img width="973" alt="image" src="https://github.com/adalessa/laravel.nvim/assets/31175326/fc27e8a4-2b66-453a-a051-fc01ef08c7da">

**Comment by kcaashish** [comment]
Possibly similar to #4 ?

**Comment by dorkster100** [comment]
You are missing a dependency: 
    "tpope/vim-dotenv",

**Comment by kcaashish** [comment]
I am not using docker-compose no. I just added the dependency you mentioned but am still getting the same error.

**Comment by kcaashish** [comment]
This happens during the initialization step, as soon as I open a php file, I don't run the application. I used to use `:Laravel routes` and it worked no problem, without running the application. I don't use other Artisan commands.

**Comment by kcaashish** [comment]
So all I am saying is, the plugin doesn't initialize after loading.

**Comment by dorkster100** [comment]
This error will be fixed once the pr is accepted

**Comment by bstavenuiter** [comment]
hey, i got the same messages as above when trying out the initial setup. 

I am not running the application as well. I mainly use valet to access my apps locally, so no docker or docker compose. 

Would really love to try out this plugin as I work with laravel for years now.

**Comment by dorkster100** [comment]
Hello, the message will be fixed as soon as pr is merged, however this will not fix your valet setup. For this you will probably have to do some custom configuration, I will look at valet documentation later, can you tell me how you are running the application locally?
How do you run artisan commands?

**Comment by dorkster100** [comment]
try setting `NVIM_LARAVEL_ENV` in `.env` to `local` then.
