### ISSUE TITLE
Plugin is assuming docker is running, even with NVIM_LARAVEL_ENV=local

### ISSUE THREAD

**Issue by bstavenuiter** [adalessa/laravel.nvim#30]
It seems that this plugin is checking if docker is running when calling a command like `Laravel artisan` or `Laravel routes`. 

I am setting the .env var NVIM_LARAVEL_ENV=local to let the plugin know I am running everything locally

[laravel] [ERROR 09:08:57] .../.local/share/nvim/lazy/laravel.nvim/lua/laravel/dev.lua:33: 1684739291 app.routes(): stderr { 'time="2023-05-22T09:08:57+02:00" level=warning msg="network devspread_server: network.external.name is deprecated. Please set network.name with external: true"', "Cannot connect to the Docker daemon at unix:///[[REDACTED]].
Is the docker daemon running?" }

**Comment by adalessa** [comment]
Hi, do you have installed the `"tpope/vim-dotenv",` to be able to read from the `.env` file ?

**Comment by adalessa** [comment]
In the last update I have added a command for getting the environment configuration please run :LaravelInfo command.
Not this require a new dependency new in the readme     "MunifTanjim/nui.nvim".

**Comment by bstavenuiter** [comment]
Getting some results now! 

Laravel and Artisan commands now work. 

Specially love the send to tinker feature! Thanks!
