### ISSUE TITLE
[Bug] Laravel.nvim hits error when trying to run commands using other plugins

### ISSUE THREAD

**Issue by naquad** [adalessa/laravel.nvim#31]
So there's this somewhat annoying error:

```
E5108: Error executing lua: vim/_editor.lua:0: nvim_exec2()..function <SNR>91_parse_flags[84]..<SNR>91_start[16]..<SNR>91_run[9]..<SNR>91_chdir_p
ush[3]..DirChanged Autocommands for "*": Vim(append):Error executing lua callback: .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:10
6: vendor/bin/sail: Executable not found
stack traceback:
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:106: in function 'new'
        ...are/nvim/lazy/laravel.nvim/lua/laravel/runners/async.lua:28: in function <...are/nvim/lazy/laravel.nvim/lua/laravel/runners/async.lua:
8>
        .../nvim/lazy/laravel.nvim/lua/laravel/application/init.lua:88: in function 'run'
        ...al/share/nvim/lazy/laravel.nvim/lua/laravel/commands.lua:37: in function 'load'
        .../nvim/lazy/laravel.nvim/lua/laravel/application/init.lua:68: in function 'warmup'
        ....local/share/nvim/lazy/laravel.nvim/lua/laravel/init.lua:23: in function 'setup'
        ...are/nvim/lazy/laravel.nvim/lua/laravel/_autocommands.lua:10: in function <...are/nvim/lazy/laravel.nvim/lua/laravel/_autocommands.lua:
9>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/naquad/.config/nvim/lua/plugins/nvimtree.lua:23: in function </home/naquad/.config/nvim/lua/plugins/nvimtree.lua:9>
stack traceback:
        [C]: in function 'error'
        .../.local/share/nvim/lazy/plenary.nvim/lua/plenary/job.lua:106: in function 'new'
        ...are/nvim/lazy/laravel.nvim/lua/laravel/runners/async.lua:28: in function <...are/nvim/lazy/laravel.nvim/lua/laravel/runners/async.lua:
8>
        .../nvim/lazy/laravel.nvim/lua/laravel/application/init.lua:88: in function 'run'
        ...al/share/nvim/lazy/laravel.nvim/lua/laravel/commands.lua:37: in function 'load'
        .../nvim/lazy/laravel.nvim/lua/laravel/application/init.lua:68: in function 'warmup'
        ....local/share/nvim/lazy/laravel.nvim/lua/laravel/init.lua:23: in function 'setup'
        ...are/nvim/lazy/laravel.nvim/lua/laravel/_autocommands.lua:10: in function <...are/nvim/lazy/laravel.nvim/lua/laravel/_autocommands.lua:
9>
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/naquad/.config/nvim/lua/plugins/nvimtree.lua:23: in function </home/naquad/.config/nvim/lua/plugins/nvimtree.lua:9>
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua: in function 'cmd'
        /home/naquad/.config/nvim/lua/plugins/nvimtree.lua:23: in function </home/naquad/.config/nvim/lua/plugins/nvimtree.lua:9>
```

It happens when you switch to the NvimTree window and run some custom command there. I'm not sure if there's a fix from the NvimTree side but IMHO it shouldn't be there

Laravel.nvim should be playing nice with others and do a sanity check before running anything.

STR
1. cd to a Laravel project
2. Open some PHP file
3. Open NvimTree
4. Jump between NvimTree and the buffer (may take several switches, also you may have to change the NvimTree current directory)

**Comment by adalessa** [comment]
To understand the problem, this happen when in the same session you swtich from differente projects directories. and when you return to the same you are getting the error ?

**Comment by naquad** [comment]
A single project. The edited buffer has CWD = project root, NvimTree has CWD = project root/app. When you switch to the NvimTree window the error shows up.

**Comment by adalessa** [comment]
I don't use nvim tree so I was not aware that changed the working directory. Since to find the executables uses the cwd.
This is to avoid trying to look for upper directories which are not part of the project. 

Does nvim tree leaves the working directory set as `root/app` after you open a file in that directory ?

**Comment by naquad** [comment]
No, its not. I've defined a whole bunch of custom commands for the tree (grep, formatting, moving things around, mass rename, ...) that may cause such an effect. And also sometimes I accidentally change the dir and it remembers it.

But the thing is that the plugin is choking on the directory change which shouldn't happen IMHO.
Here's another STR w/o the tree:
1. Go to Laravel project root
2. Open some file
3. Execute cmd `:lcd app`
4. BOOM!

**Comment by adalessa** [comment]
Thanks, I will review the Dirchange logic, should silently stop not throw the error.

**Comment by naquad** [comment]
Works as expected. Thank you :+1:
