### ISSUE TITLE
Going to a route doesn't work when using intelephense

### ISSUE THREAD

**Issue by WhoSayIn** [adalessa/laravel.nvim#37]
I get the following error when I try to go to a route through telescope (running `:Laravel routes`)

Even though it lists all the routes that I have, I only get this when I try to go to a route.

I switched to phpactor just to see if it works, and it works fine with phpactor. But I personally would love to keep intelephense as my lsp server.

```
Client 1 quit with exit code 1 and signal 0                                                                                                                                               
Error executing vim.schedule lua callback: ...ker/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:16: attempt to index local 'resp' (a nil value)
stack traceback:
        ...ker/start/laravel.nvim/lua/laravel/_lsp/intelephense.lua:16: in function 'go_to'
        ...te/pack/packer/start/laravel.nvim/lua/laravel/routes.lua:32: in function 'go_to'
        ...start/laravel.nvim/lua/telescope/_extensions/laravel.lua:206: in function <...start/laravel.nvim/lua/telescope/_extensions/laravel.lua:205>
```

**Comment by dorkster100** [comment]
I am using intelephense for this, but I am on an older version of laravel. Can you provide some example routes?

**Comment by WhoSayIn** [comment]
Hmm, I can't explain what happened, but now it seems to work. I'll close the issue, thanks for your reply.

To give more context, yesterday I just installed this extension and tried it for the first time. Everything worked except "going to a route". Now that also seems to be working fine.

Sorry for the noise :)

**Comment by adalessa** [comment]
No problem. if it happen again please report it.

**Comment by dorkster100** [comment]
i think i had this issue for a second and it disappeared, if it occurs again i will try to debug

**Comment by adalessa** [comment]
I think could it be the lsp not completely ready to answer and returning empty.
