### ISSUE TITLE
Route infos get cut on small screens

### ISSUE THREAD

**Issue by theoleonet** [adalessa/laravel.nvim#39]
I don't know if it's possible, but I really wish the route infos would wrap to the next line instead of disapearing at the end of the window like so
<img width="1502" alt="image" src="https://github.com/adalessa/laravel.nvim/assets/90846584/def7d8f6-e1e7-4b29-af80-c8654c334f13">

**Comment by adalessa** [comment]
Not quitely possible to wrap it, but I added a new option to set it on the line above.
please update the plugin and in your settings use 
```lua
    require("laravel").setup({
      route_info = {
        enable = true,
        position = "top",
      },
    })
```

**Comment by dorkster100** [comment]
Yes, in general it would get quite messy if you would wrap these, if you have a lot of middlewares. Maybe it would make sense to trim the namespaces or such to make it less, and have a way to get more info, maybe some command, not sure.

**Comment by adalessa** [comment]
Yeah I don't think wrapping is a good idea either, but as far as I know there is no way to wrap virtual text in that way. I think the idea on  the line before is good, I am currently using it. I will close the issue now. 
For the case if you have a lot of middleware using multiple virtual lines is an option.
Maybe habe a short version that is in the same line as now only having method and uri, and a more detailed version that is hows on virtual lines above it.
