### ISSUE TITLE
Error with nil variable on startup neovim in a Laravel project

### ISSUE THREAD

**Issue by malisoft** [adalessa/laravel.nvim#4]
![image](https://user-images.githubusercontent.com/55772887/231427189-8ca46f2e-9324-450e-bd77-231a2c2f3822.png)

this problem appears since today trying to open a laravel project but the plugin is still running.
Note: i did an update with lazy yesterday

**Comment by adalessa** [comment]
Thanks for the report.
This is due neovim changing an internal API `treesitter` I have added a check for this. Please update to the latest version of the plugin with lazy and try again.

**Comment by adalessa** [comment]
I will close this now, feel free to comment and we can re open if necessary. Regards.
