### ISSUE TITLE
Request for Argument when Opening Tinker

### ISSUE THREAD

**Issue by josefo727** [adalessa/laravel.nvim#49]
**Request for Argument when Opening Tinker**

When executing the command to open Tinker from Telescope, it prompts for an additional argument. If I enter anything, it generates an error, but if I press [Esc], it allows me to access Tinker normally.

![image](https://github.com/adalessa/laravel.nvim/assets/39111029/3b3cc2dc-6c38-4bef-b99d-54aa53392abd)

**Comment by dorkster100** [comment]
@josefo727 This is not a bug, the tinker command has arguments you can provide, and the argument name is `include` it lets you provide files that you want to include on startup of the tinker, this is optional though.

**Comment by adalessa** [comment]
Option for `skip_args` was added on v2.
