### ISSUE TITLE
Request for Packer Instructions in Addition to Lazy.nvim

### ISSUE THREAD

**Issue by FadeDreams** [adalessa/laravel.nvim#50]
I hope this message finds you well. I'm a user of adalessa/laravel.nvim, and I've been greatly enjoying the functionality it offers for Laravel development within Neovim. Firstly, thank you for developing such a useful plugin!

I wanted to bring up a suggestion for enhancing the user experience. Currently, the plugin includes instructions for integration with Lazy.nvim in the repository's README. However, I noticed that there are no instructions provided for users who prefer to use the Packer plugin manager. Packer is gaining popularity as a lightweight and efficient plugin manager, and having instructions for Packer integration would help users who opt for this manager.

I have attempted to integrate adalessa/laravel.nvim with Packer using the following configuration:
```
  use {
    "adalessa/laravel.nvim",
    requires = {
      "nvim-telescope/telescope.nvim",
      "tpope/vim-dotenv",
      "MunifTanjim/nui.nvim",
    },
    cmd = { "Sail", "Artisan", "Composer", "Npm", "Yarn", "Laravel" },
    keys = {
      { "<leader>la", ":Laravel artisan<cr>" },
      { "<leader>lr", ":Laravel routes<cr>" },
      {
        "<leader>lt",
        function()
          require("laravel.tinker").send_to_tinker()
        end,
        mode = "v",
        desc = "Laravel Application Routes",
      },
    },
    event = { "VeryLazy" },
    config = function()
      require("laravel").setup()
      require("telescope").load_extension "laravel"
    end,
  }
```
 However, this configuration does not seem to work as expected. I've verified that my Packer installation is functional and have successfully integrated other plugins with it.
Thank you for your consideration.

**Comment by dorkster100** [comment]
@FadeDreams please provide more information, what does not seem to work for you? The plugin is a bit tricky since it uses your local laravel setup (there are multiple possibilities like sail, docker or linux installation, how are you running your project, please provide more info with errors, etc.

**Comment by FadeDreams** [comment]
I trust this message finds you in good health. Previously, I had been encountering certain issues while using the Packer plugin manager. However, I've since made the switch to Lazy.nvim, and I'm pleased to report that my previous problems have been completely resolved. This transition has significantly improved my overall experience with the plugin and my Neovim setup as a whole. Your efforts in maintaining and improving this plugin are highly appreciated, and I'm excited to see how it continues to evolve.

**Comment by dorkster100** [comment]
you can probably close the issue for now, when someone encounters it again, we then can try to figure out the issue.
