### ISSUE TITLE
Help needed laravel.environment.resolver

### ISSUE THREAD

**Issue by Dante983** [adalessa/laravel.nvim#51]
Hey everyone, i'm kinda new to the nvim, lazy, etc, so im having some troubles setting up laravel.environment.resolver .
I'm getting an error module laravel.environment.resolver not found.
Can someone guide me on how to set this up, where do i need to pass 'NVIM_LARAVEL_ENV' variable so that the plugin can read it. 
Sorry if this is stupid question :D 

<img width="938" alt="image" src="https://github.com/adalessa/laravel.nvim/assets/51093125/6e29838b-3e08-4c63-8301-9f2ea8e132f6">

**Comment by adalessa** [comment]
Hey since there is no more comments I assume that it was solve, if not please open it again or a new one.
