### ISSUE TITLE
Docker compose not working anymore

### ISSUE THREAD

**Issue by dorkster100** [adalessa/laravel.nvim#58]
The problem is that compose executable does not exist for me, is there a reason it is not `docker-compose`? Replacing compose with docker-compose in this file fixes this issue for me.

```php
  create_user_command("DockerCompose", "compose", {
    up = function()
      api.async(
        "compose",
        { "up", "-d" },
        ---@param response ApiResponse
        function(response)
          if response:failed() then
            vim.notify(response:prettyErrors(), vim.log.levels.ERROR)
          else
            vim.notify("Compose Up Completed", vim.log.levels.INFO)
            status.refresh()
          end
        end
      )
    end,
```

On another note, `create_user_command` for some reason does register `DockerCompose`  every other time even with non existing executable `compose`, so there is also some issue with that.

**Comment by adalessa** [comment]
Hi @dorkster100 I think I know the problem. The usage of compose is intentional. is defined to be mapped in the configuration. I don't use docker-compose because it was deprecated and from the docs is expected to use `docker compose`.
What I think it happen is that the wrong environment was being loaded. Could you check the `:checkhealth laravel` that should show which environment was being use ?
I notice that lua does not respect the index for alphanumeric keys so I have to do a little refactor so the order in the config is respected.
the fix is live

**Comment by dorkster100** [comment]
```
laravel: require("laravel.health").check()

Laravel ~
- OK fd installed
- OK rg installed

Environment ~
- OK Environment setup successful
- Name: local
- Condition: 
- {
  executable = { "php" }
  }
- Commands: 
- {}

Composer Dependencies ~
- OK Composer dependency `doctrine/dbal` is installed
- OK Composer dependency `laravel/tinker` is installed
```

**Comment by dorkster100** [comment]
@adalessa after update it got better, it recognized the DockerCompose env, but now the commands dont work `Error executing lua callback [NULL]`, and again it fixed setting `docker-compose` for me, i think he does not recognize it as executible otherwise.

**Comment by adalessa** [comment]
does your version of docker have the sub command compose `docker compose`?

**Comment by adalessa** [comment]
From the documentation the way to run docker compose is like that https://docs.docker.com/compose/gettingstarted/#step-4-build-and-run-your-app-with-compose.
The settings yes it's for case like that change the compose command as you may need and the container exec.

**Comment by dorkster100** [comment]
yes my version works with `docker compose` and all docker environvent commands work like `DockerCompose ps`

here is health now:
```
laravel: require("laravel.health").check()

Laravel ~
- OK fd installed
- OK rg installed

Environment ~
- OK Environment setup successful
- Name: docker-compose
- Condition: 
- {
  executable = { "docker" },
  file_exists = { "docker-compose.yml" }
  }
- Commands: 
- { {
  commands = { "php", "composer", "npm" },
  docker = {
  container = {
  default = "app",
  env = "APP_SERVICE"
  },
  exec = { "docker", "compose", "exec", "-it" }
  }
  },
  compose = { "docker", "compose" }
  }
```

**Comment by adalessa** [comment]
what command gives you the error ?

**Comment by dorkster100** [comment]
any `Laravel` runner command, for example `Laravel artisan`, just to be clear first health that i posted was with previous commit, sorry to confuse.

**Comment by adalessa** [comment]
Yes I realize that. To confirm the problem if in the config you change to 
```lua
{
      name = "docker-compose",
      condition = {
        file_exists = { "docker-compose.yml" },
        executable = { "docker" },
      },
      commands = {
        compose = { "docker-compose" },
        {
          commands = { "php", "composer", "npm" },
          docker = {
            container = {
              env = "APP_SERVICE",
              default = "app",
            },
            exec = { "docker-compose", "exec", "-it" },
          },
        },
      },
    }
```
With this should be using only `docker-compose`

**Comment by dorkster100** [comment]
`Laravel artisan` now works, `Laravel routes` still fail with same error

**Comment by adalessa** [comment]
I will have to create an environment to test, I tested with sail and local with no issue.
I will appreciate if you have some examples of your docker configuration that you could share.

**Comment by dorkster100** [comment]
Is there some sort of cache? Because now artisan works with no changes, but routes does not

**Comment by adalessa** [comment]
The caches are clean on setup, you can run `:Larave cache:clean` to trigger it. Routes could be if the state of the aplication could not retrieve the routes. Something wrong on the web.php for example.

**Comment by dorkster100** [comment]
Yes, you were right I actually had some errors with composer. Would be nice to have some error output. okay, now it seems to work.

**Comment by adalessa** [comment]
Agree, I will check on that.

**Comment by adalessa** [comment]
I have pushed a version that should report the error from the artisan commands.
I think with that we can close the ticket for now.
