### ISSUE TITLE
''null-ls" is missing in dependency in the dependency list in the installation guide

### ISSUE THREAD

**Issue by t0mri** [adalessa/laravel.nvim#70]
TLDR; [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) is required by this plugin, so add it in the dependency list.
```lua
...
dependencies = {
    "nvim-telescope/telescope.nvim",
    "tpope/vim-dotenv",
    "MunifTanjim/nui.nvim",
    "jose-elias-alvarez/null-ls.nvim"
  },
...
```
Details:
[null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) is required by this plugin (laravel.nvim) as stated in [here](https://github.com/adalessa/laravel.nvim/blob/main/lua/laravel/null_ls/completion/init.lua) (`laravel.nvim/lua/laravel/null_ls/completion/init.lua:18`). It shouts if `null-ls` isn't installed (refer the image below).

![image](https://github.com/adalessa/laravel.nvim/assets/123792488/3c9de78e-ae85-49a6-aed7-b14bf13ba13c)

**Comment by adalessa** [comment]
Thanks for reporting this. I will update, and fix since should be optional.
