### ISSUE TITLE
 there are many problems in this plugin

### ISSUE THREAD

**Issue by Naimul007A** [adalessa/laravel.nvim#75]
![image](https://github.com/adalessa/laravel.nvim/assets/112851392/744ba89d-147b-4021-89eb-51383af2cbfe)

please solved this.

**Comment by adalessa** [comment]
Hi, There is nothing to solve here. This command requires doctrine dbal install in your laravel project. Is the same if you try to run php artisan model:show. The plugin it self will not install it for you. In the documentation it states that is required for this. If you run a `:checkhealth laravel` it also lets you know and finally the error when you are trying to run it. 
Also the plugins includes a recipe `:Laravel recipes` to make it easy to install which will run the composer command for you.

**Comment by Naimul007A** [comment]
Thanks
