### ISSUE TITLE
Ability to configure altenative picker (fzf-lua)

### ISSUE THREAD

**Issue by caliguIa** [adalessa/laravel.nvim#87]
Hi, it would be great if we could configure alternative pickers (fzf-lua) instead of telescope.

**Comment by adalessa** [comment]
Hey, I have not used fzf picker, how this is built it can be extended, in the development branch there is the concept of revolvers that will easily provide de list to be use in the pickers. What will need to be review are the actions.

**Comment by caliguIa** [comment]
Thanks, I will attempt to take a look soon. Cheers

**Comment by adalessa** [comment]
@caliguIa if you have any question related to the plugin feel free to do it, I can provide some support to it.

**Comment by caliguIa** [comment]
Thanks @adalessa appreciate it, I will attempt to take a look at it this week if I get the time.

**Comment by rqpt** [comment]
I'm interested in tackling this issue, as I also prefer using fzf-lua over telescope these days.

**Comment by adalessa** [comment]
@rqpt nice to hear the interest, just FYI I am working on a re-design on the structure, with a container system similar to laravel one, in case you want to take a look to it is on the feature/container branch

**Comment by Bleksak** [comment]
The easiest way to do this, is to use vim.ui.select instead of telescope integration and register fzf/telescope as vim.ui.select

**Comment by Bleksak** [comment]
Hi all, we finally managed to at least add vim.ui.select as the picker in the development branch. If you still want this feature, please try it out.

vim.ui.select is a very basic picker, it doesn't support previews

I will take a look at fzf this week

**Comment by adalessa** [comment]
It's already on master, I pulled the trigger, now is tagged as 3.0

**Comment by Dieal** [comment]
> It's already on master, I pulled the trigger, now is tagged as 3.0

Sorry for the ignorance, but how do I enable it? I can't find it anywhere in the docs

**Comment by Bleksak** [comment]
@Dieal this should do it:
```
opts = {
  features = {
    pickers = {
      provider = 'fzf-lua'
    }
  }
}
```
