### ISSUE TITLE
Weird issue which prevent to work

### ISSUE THREAD

**Issue by MrMic** [adalessa/laravel.nvim#94]
Hi,

I have installed your plugin through AstroNvim and I got this weird issue:
```
[null-ls] failed to run generator: ...share/AstroNvim4/lazy/laravel.nvim/lua/laravel/paths.lua:25: attempt to index local 'path' (a nil value)
```
I got laravel-dev-generators in my path.

Can you help me to fix this, because it is not working at all. 😥

**Comment by Ercules76** [comment]
Hi @MrMic i've the same issue, how you fixed it? TY

**Comment by MrMic** [comment]
Hi @Ercules76, 

If I remember well I put laravel-dev-generators in the path where neovim looks for it.

You have to discover the directories where your neovim look for binaries. And then 
put laravel-dev-generators in one of them.
It is often closely related to the PATH in your shell.

I hope it will drive you in the right direction.

Rgds,
