### ISSUE TITLE
Allow for completion of config function file and key names

### ISSUE THREAD

**Issue by adaviloper** [adalessa/laravel.nvim#95]
Any thoughts on being able to generate a source for providing `config()` function file name and values?

Something similar to detecting `config()` calls, suggesting config file names and then start suggesting nested array key values after every dot.

**Comment by adalessa** [comment]
Hey, Yeah I have it in the new version with cmp integration, since null ls was deprecated still considering if that is the best option, since cmp is most use I have implemented on it. hopefully soon will be release if you want it there is the wrong in progress in the feature/container branch.

**Comment by adaviloper** [comment]
Is there some setting I'm supposed to add? From what I can tell it's already included in the completions and providers list of services.

When I type `config(|)` (pipe is cursor position), the only `cmp` suggestions I'm getting are for the current buffer.

**Comment by adalessa** [comment]
did you add the source laravel to you cmp config ? 
you can run the command :CmpStatus to check if is enable and registered.
![2024-08-04_07-10_1](https://github.com/user-attachments/assets/9ae63ff4-1c9c-430a-9d33-5918937885a9)
![2024-08-04_07-10](https://github.com/user-attachments/assets/5c12e00c-ec6f-4499-8087-529bae2f1ddb)

**Comment by adaviloper** [comment]
Thanks, that's what I was missing! You've done an incredible job with this plugin!

**Comment by adalessa** [comment]
Hey thanks for the kind words. I enjoy working on it and it's nice that other find it useful as well.
