### ISSUE TITLE
service "laravel.test" is not running

### ISSUE THREAD

**Issue by philharmonie** [adalessa/laravel.nvim#99]
I installed the plugin as described and when I hit `<leader>la` I get the error
```
service "laravel.test" is not running
```

As I don't know where this is related to, it's difficult to provide good context.

I'm using Nvim with Lazyvim, and Laravel with Herd on a Mac.

**Comment by philharmonie** [comment]
Sorry, I am not using sail at all. As time has passed, the error message changed to: `Sail not running` for `<leader>lm` it is `Error executing Lua callback: [NULL]`

**Comment by adalessa** [comment]
Hey, the plugin tries to get it by the context, by default laravel comes with the sail package installed, and look for a docker-compose.yaml in the root directory, if that is the case, that could be the reason.

**Comment by philharmonie** [comment]
Indeed I have a `docker-compose.yaml` in the root, but not for sail. Anyhow, if I remove it, I get
```
no configuration file provided: not found
Sail is not running.
You may Sail using the following commands: './vendor/bin/sail up' or './vendor/bin/sail up -d'
```

**Comment by adalessa** [comment]
@philharmonie have you tried what I first suggested of the environment variable in your .env file ?
